# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='media.MediaTagModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
