# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.TextField(blank=True, choices=[('None', ''), ('Test', 'test')]),
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.TextField(blank=True, choices=[('None', ''), ('Test', 'test')]),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.TextField(blank=True, choices=[('None', ''), ('Test', 'test')]),
        ),
    ]
