# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20171008_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='category',
        ),
        migrations.AddField(
            model_name='audio',
            name='category',
            field=models.ManyToManyField(to='media.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='media.Category'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(to='media.Category'),
        ),
    ]
