# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20171011_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericobjectrelation',
            name='related_audio',
        ),
        migrations.AddField(
            model_name='genericobjectrelation',
            name='related_audio',
            field=models.ManyToManyField(blank=True, null=True, to='media.Audio'),
        ),
        migrations.RemoveField(
            model_name='genericobjectrelation',
            name='related_image',
        ),
        migrations.AddField(
            model_name='genericobjectrelation',
            name='related_image',
            field=models.ManyToManyField(blank=True, null=True, to='media.Image'),
        ),
        migrations.RemoveField(
            model_name='genericobjectrelation',
            name='related_video',
        ),
        migrations.AddField(
            model_name='genericobjectrelation',
            name='related_video',
            field=models.ManyToManyField(blank=True, null=True, to='media.Video'),
        ),
    ]
