# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20171011_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericobjectrelation',
            name='related_audio',
            field=models.ManyToManyField(blank=True, to='media.Audio'),
        ),
        migrations.AlterField(
            model_name='genericobjectrelation',
            name='related_image',
            field=models.ManyToManyField(blank=True, to='media.Image'),
        ),
        migrations.AlterField(
            model_name='genericobjectrelation',
            name='related_video',
            field=models.ManyToManyField(blank=True, to='media.Video'),
        ),
    ]
