# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20171011_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='relation',
            field=models.ManyToManyField(to='media.GenericObjectRelation'),
        ),
        migrations.AddField(
            model_name='video',
            name='relation',
            field=models.ManyToManyField(to='media.GenericObjectRelation'),
        ),
    ]
