# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_auto_20171011_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.ManyToManyField(blank=True, to='media.Category'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='relation',
            field=models.ManyToManyField(blank=True, to='media.GenericObjectRelation'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='media.MediaTagModel'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(blank=True, to='media.Category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='relation',
            field=models.ManyToManyField(blank=True, to='media.GenericObjectRelation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='media.MediaTagModel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(blank=True, to='media.Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='relation',
            field=models.ManyToManyField(blank=True, to='media.GenericObjectRelation'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='media.MediaTagModel'),
        ),
    ]
